"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CATCH_ALL = exports.JSON_CONTROLLER = exports.HTTP_CODE = exports.ON_UNDEFINED = exports.HEADER_PARAM = exports.PARAM = exports.BODY = exports.DELETE = exports.PUT = exports.GET = exports.POST = exports.TRANSFORM_STRING_STRIP_PREFIX = exports.TRANSFORM_BOOLEAN_ARRAY = exports.TRANSFORM_NUMBER_ARRAY = exports.TRANSFORM_STRING_ARRAY = exports.TRANSFORM_OBJECT_ARRAY = exports.TRANSFORM_DATE_TIME_STRING = exports.TRANSFORM_OBJECT = exports.TRANSFORM_BOOLEAN = exports.TRANSFORM_NUMBER = exports.TRANSFORM_STRING = exports.TYPE = exports.EXPOSE = exports.EXCLUDE = exports.IS_DATE_TIME = exports.IS_DATE = exports.IS_PHONE_NUMBER = exports.IS_EMAIL = exports.IS_ARRAY = exports.IS_OBJECT = exports.IS_BOOLEAN = exports.IS_NUMBER = exports.IS_STRING = exports.IS_NOT_BLANK = exports.IS_NOT_EMPTY = exports.IS_OPTIONAL = exports.IS_DEFINED = void 0;
/** Decorator constants */
exports.IS_DEFINED = "IsDefined";
exports.IS_OPTIONAL = "IsOptional";
exports.IS_NOT_EMPTY = "IsNotEmpty";
exports.IS_NOT_BLANK = "IsNotBlank";
exports.IS_STRING = "IsString";
exports.IS_NUMBER = "IsNumber";
exports.IS_BOOLEAN = "IsBoolean";
exports.IS_OBJECT = "IsObject";
exports.IS_ARRAY = "IsArray";
exports.IS_EMAIL = "IsEmail";
exports.IS_PHONE_NUMBER = "IsPhoneNumber";
exports.IS_DATE = "IsDate";
exports.IS_DATE_TIME = "IsDateTime";
exports.EXCLUDE = "Exclude";
exports.EXPOSE = "Expose";
exports.TYPE = "Type";
exports.TRANSFORM_STRING = "TransformString";
exports.TRANSFORM_NUMBER = "TransformNumber";
exports.TRANSFORM_BOOLEAN = "TransformBoolean";
exports.TRANSFORM_OBJECT = "TransformObject";
exports.TRANSFORM_DATE_TIME_STRING = "TransformDatetimeString";
exports.TRANSFORM_OBJECT_ARRAY = "TransformObjectArray";
exports.TRANSFORM_STRING_ARRAY = "TransformStringArray";
exports.TRANSFORM_NUMBER_ARRAY = "TransformNumberArray";
exports.TRANSFORM_BOOLEAN_ARRAY = "TransformBooleanArray";
exports.TRANSFORM_STRING_STRIP_PREFIX = "TransformStringStripPrefix";
exports.POST = "Post";
exports.GET = "Get";
exports.PUT = "Put";
exports.DELETE = "Delete";
exports.BODY = "Body";
exports.PARAM = "Param";
exports.HEADER_PARAM = "HeaderParam";
exports.ON_UNDEFINED = "OnUndefined";
exports.HTTP_CODE = "HttpCode";
exports.JSON_CONTROLLER = "JsonController";
exports.CATCH_ALL = "CatchAll";
//# sourceMappingURL=decorators.const.js.map