export enum UoConnectors {
    "minion-net-connector" = "minion-net-connector",
    "ms-auth-connector" = "ms-auth-connector",
    "ms-configuration-server-connector" = "ms-configuration-server-connector",
    "ms-content-connector" = "ms-content-connector",
    "ms-guests-connector" = "ms-guests-connector",
    "ms-hotels-connector" = "ms-hotels-connector",
    "ms-neuron-connector" = "ms-neuron-connector",
    "ms-notifications-connector" = "ms-notifications-connector",
    "ms-notifications-legacy-connector" = "ms-notifications-legacy-connector",
    "ms-orders-connector" = "ms-orders-connector",
    "ms-pay-connector" = "ms-pay-connector",
    "ms-references-connector" = "ms-references-connector",
    "ms-travel-party-connector" = "ms-travel-party-connector",
    "ms-wallet-connector" = "ms-wallet-connector",
}
