/** Template file paths */
export const CLASS_TEMPLATE = "./templates/source-file-components/class.txt";
export const DECORATED_CLASS_TEMPLATE = "./templates/source-file-components/decorated-class.txt";
export const METHOD_TEMPLATE = "./templates/source-file-components/method.txt";
export const DECORATED_METHOD_TEMPLATE = "./templates/source-file-components/decorated-method.txt";
export const FIELD_TEMPLATE = "./templates/source-file-components/field.txt";
export const DATABASE_ADAPTER_CONFIG_TEMPLATE = "./templates/source-file-components/database-adapter-config.txt";
export const REDIS_OPTIONS_TEMPLATE = "./templates/source-file-components/redis-options.txt";
export const DESCRIBE_BLOCK_TEMPLATE = "./templates/test-file-components/describe-block.txt";
export const SPEC_FILE_TEMPLATE = "./templates/test-file-components/spec-file.txt";
export const APP_TS_FILE_TEMPLATE = "./templates/config-files/app-ts.txt";
export const INDEX_TS_FILE_TEMPLATE = "./templates/config-files/index-ts.txt";
export const PLAIN_FILE_TEMPLATE = "./templates/source-file-components/plain-file.txt";