"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IS_STRING = exports.IS_NOT_BLANK = exports.IS_NOT_EMPTY = exports.IS_OPTIONAL = exports.IS_DEFINED = exports.SINON = exports.MOCHA = exports.CHAI = exports.NANO = exports.UO_COUCHDB_CONNECTOR_LIB = exports.UO_TRANSFORM_DECORATORS_LIB = exports.UO_STATUS_CODE_LIB = exports.UO_VALIDATION_DECORATOR_LIB = exports.ROUTING_CONTROLLERS_LIB = exports.CLASS_TRANSFORMER_LIB = exports.CLASS_VALIDATOR_LIB = exports.ENV_FILE_PATH = exports.LOGGER_FILE_PATH = exports.INDEX_FILE_PATH = exports.APP_FILE_PATH = exports.VALIDATION_MESSAGES_FILE = exports.ADAPTER_TEST_FILE_SUFFIX = exports.SERVICE_TEST_FILE_SUFFIX = exports.CONTROLLER_TEST_FILE_SUFFIX = exports.CONNECTOR_FILE_SUFFIX = exports.DATABASE_ADAPTER_FILE_SUFFIX = exports.SERVICE_FILE_SUFFIX = exports.CONTROLLER_FILE_SUFFIX = exports.API_TESTS_PATH_SUFFIX = exports.CONFIG_DIR = exports.VALIDATION_MESSAGES_FILE_DIR = exports.CONNECTORS_MODELS_DIR = exports.ADAPTER_TESTS_DIR = exports.ADAPTER_MODELS_DIR = exports.ENTITY_MODELS_DIR = exports.API_MODELS_DIR = exports.CONNECTORS_DIR = exports.ADAPTERS_DIR = exports.APIS_DIR = exports.SRC_DIR = exports.DATABASE_ADAPTER_CONFIG_TEMPLATE = exports.INDEX_TS_FILE_TEMPLATE = exports.APP_TS_FILE_TEMPLATE = exports.SPEC_FILE_TEMPLATE = exports.DESCRIBE_BLOCK_TEMPLATE = exports.FIELD_TEMPLATE = exports.DECORATED_METHOD_TEMPLATE = exports.METHOD_TEMPLATE = exports.DECORATED_CLASS_TEMPLATE = exports.CLASS_TEMPLATE = void 0;
exports.CORRELATION_ID_PARAM_DESCR = exports.PARAMETERS_REFERENCE = exports.OBJECTS_REFERENCE = exports.PERSISTENT_MODEL_LABEL = exports.EXPECT = exports.ENV_VAR_NAME = exports.LOGGER_VAR_NAME = exports.DOCUMENT_INSERT_RESPONSE = exports.COUCHDB_CONNECTOR = exports.CONFIGURE_DATABASE = exports.CATCH_ALL = exports.JSON_CONTROLLER = exports.HTTP_CODE = exports.ON_UNDEFINED = exports.HEADER_PARAM = exports.PARAM = exports.BODY = exports.DELETE = exports.PUT = exports.GET = exports.POST = exports.TRANSFORM_STRING_STRIP_PREFIX = exports.TRANSFORM_BOOLEAN_ARRAY = exports.TRANSFORM_NUMBER_ARRAY = exports.TRANSFORM_STRING_ARRAY = exports.TRANSFORM_OBJECT_ARRAY = exports.TRANSFORM_DATE_TIME_STRING = exports.TRANSFORM_OBJECT = exports.TRANSFORM_BOOLEAN = exports.TRANSFORM_NUMBER = exports.TRANSFORM_STRING = exports.TYPE = exports.EXPOSE = exports.EXCLUDE = exports.IS_DATE_TIME = exports.IS_DATE = exports.IS_PHONE_NUMBER = exports.IS_EMAIL = exports.IS_ARRAY = exports.IS_OBJECT = exports.IS_BOOLEAN = exports.IS_NUMBER = void 0;
/** Template file paths */
exports.CLASS_TEMPLATE = "./templates/source-files/class.txt";
exports.DECORATED_CLASS_TEMPLATE = "./templates/source-files/decorated-class.txt";
exports.METHOD_TEMPLATE = "./templates/source-files/method.txt";
exports.DECORATED_METHOD_TEMPLATE = "./templates/source-files/decorated-method.txt";
exports.FIELD_TEMPLATE = "./templates/source-files/field.txt";
exports.DESCRIBE_BLOCK_TEMPLATE = "./templates/tests/describe-block.txt";
exports.SPEC_FILE_TEMPLATE = "./templates/tests/spec-file.txt";
exports.APP_TS_FILE_TEMPLATE = "./templates/config-files/app-ts.txt";
exports.INDEX_TS_FILE_TEMPLATE = "./templates/config-files/index-ts.txt";
exports.DATABASE_ADAPTER_CONFIG_TEMPLATE = "./templates/source-files/database-adapter-config.txt";
/** Project file paths, prefixes and suffixes */
exports.SRC_DIR = "src";
exports.APIS_DIR = "src/api";
exports.ADAPTERS_DIR = "src/adapters/database";
exports.CONNECTORS_DIR = "src/adapters/connectors";
exports.API_MODELS_DIR = "src/models/api";
exports.ENTITY_MODELS_DIR = "src/models/entity";
exports.ADAPTER_MODELS_DIR = "src/models/adapter";
exports.ADAPTER_TESTS_DIR = "src/adapters/database/tests";
exports.CONNECTORS_MODELS_DIR = "src/models/adapters/connectors";
exports.VALIDATION_MESSAGES_FILE_DIR = "src/models/api/shared";
exports.CONFIG_DIR = "src/config";
exports.API_TESTS_PATH_SUFFIX = "/tests";
exports.CONTROLLER_FILE_SUFFIX = "controller.ts";
exports.SERVICE_FILE_SUFFIX = "service.ts";
exports.DATABASE_ADAPTER_FILE_SUFFIX = "database.adapter.ts";
exports.CONNECTOR_FILE_SUFFIX = "adapter.ts";
exports.CONTROLLER_TEST_FILE_SUFFIX = "controller.spec.ts";
exports.SERVICE_TEST_FILE_SUFFIX = "service.spec.ts";
exports.ADAPTER_TEST_FILE_SUFFIX = "adapter.spec.ts";
exports.VALIDATION_MESSAGES_FILE = "validation-messages.const";
exports.APP_FILE_PATH = "src/app.ts";
exports.INDEX_FILE_PATH = `${exports.CONFIG_DIR}/index.ts`;
exports.LOGGER_FILE_PATH = exports.APP_FILE_PATH;
exports.ENV_FILE_PATH = exports.INDEX_FILE_PATH;
/** Libraries used in UO microservices repos */
exports.CLASS_VALIDATOR_LIB = "class-validator";
exports.CLASS_TRANSFORMER_LIB = "class-transformer";
exports.ROUTING_CONTROLLERS_LIB = "routing-controllers";
exports.UO_VALIDATION_DECORATOR_LIB = "@uo/validation-decorators";
exports.UO_STATUS_CODE_LIB = "@uo/status-codes";
exports.UO_TRANSFORM_DECORATORS_LIB = "@uo/transform-decorators";
exports.UO_COUCHDB_CONNECTOR_LIB = "@uo/couchdb-connector";
exports.NANO = "nano";
exports.CHAI = "chai";
exports.MOCHA = "mocha";
exports.SINON = "sinon";
/** Decorator constants */
exports.IS_DEFINED = "IsDefined";
exports.IS_OPTIONAL = "IsOptional";
exports.IS_NOT_EMPTY = "IsNotEmpty";
exports.IS_NOT_BLANK = "IsNotBlank";
exports.IS_STRING = "IsString";
exports.IS_NUMBER = "IsNumber";
exports.IS_BOOLEAN = "IsBoolean";
exports.IS_OBJECT = "IsObject";
exports.IS_ARRAY = "IsArray";
exports.IS_EMAIL = "IsEmail";
exports.IS_PHONE_NUMBER = "IsPhoneNumber";
exports.IS_DATE = "IsDate";
exports.IS_DATE_TIME = "IsDateTime";
exports.EXCLUDE = "Exclude";
exports.EXPOSE = "Expose";
exports.TYPE = "Type";
exports.TRANSFORM_STRING = "TransformString";
exports.TRANSFORM_NUMBER = "TransformNumber";
exports.TRANSFORM_BOOLEAN = "TransformBoolean";
exports.TRANSFORM_OBJECT = "TransformObject";
exports.TRANSFORM_DATE_TIME_STRING = "TransformDatetimeString";
exports.TRANSFORM_OBJECT_ARRAY = "TransformObjectArray";
exports.TRANSFORM_STRING_ARRAY = "TransformStringArray";
exports.TRANSFORM_NUMBER_ARRAY = "TransformNumberArray";
exports.TRANSFORM_BOOLEAN_ARRAY = "TransformBooleanArray";
exports.TRANSFORM_STRING_STRIP_PREFIX = "TransformStringStripPrefix";
exports.POST = "Post";
exports.GET = "Get";
exports.PUT = "Put";
exports.DELETE = "Delete";
exports.BODY = "Body";
exports.PARAM = "Param";
exports.HEADER_PARAM = "HeaderParam";
exports.ON_UNDEFINED = "OnUndefined";
exports.HTTP_CODE = "HttpCode";
exports.JSON_CONTROLLER = "JsonController";
exports.CATCH_ALL = "CatchAll";
/** Import constants */
exports.CONFIGURE_DATABASE = "ConfigureDatabase";
exports.COUCHDB_CONNECTOR = "CouchdbConnector";
exports.DOCUMENT_INSERT_RESPONSE = "DocumentInsertResponse";
exports.LOGGER_VAR_NAME = "logger";
exports.ENV_VAR_NAME = "env";
exports.EXPECT = "expect";
/** Swagger related constants */
exports.PERSISTENT_MODEL_LABEL = "crud";
exports.OBJECTS_REFERENCE = "components.schemas.";
exports.PARAMETERS_REFERENCE = "components.parameters.";
/** Other constants */
exports.CORRELATION_ID_PARAM_DESCR = "correlationId the id used for tracking the flow of a request";
//# sourceMappingURL=constants.js.map